CUDA_VISIBLE_DEVICES=4 python run_debug.py \
    --cond_modal text \
    --training_stage finetune_debug \
    --save_folder ./verbalts_orig_save/istanbul_my_caps/text2ts_msmdiffmv \
    --model_diff_config_path configs/istanbul_debug/diff/model_text2ts_dep.yaml \
    --model_cond_config_path configs/istanbul_debug/cond/text_msmdiffmv.yaml \
    --train_config_path configs/istanbul_debug/train.yaml \
    --evaluate_config_path configs/istanbul_debug/evaluate.yaml \
    --data_folder /playpen/haochenz/LitsDatasets/128_len_ts/istanbul_traffic \
    --clip_folder "" \
    --multipatch_num 3 \
    --L_patch_len 2 \
    --base_patch 4 \
    --epochs 2500 \
    --batch_size 512 \
    --clip_cache_path "" \
    --samples_name "samples.pt"