CUDA_VISIBLE_DEVICES=5 python run.py \
    --cond_modal text \
    --training_stage finetune \
    --save_folder ./verbalts_orig_save/synth_u/text2ts_msmdiffmv \
    --model_diff_config_path configs/synth_u/diff/model_text2ts_dep.yaml \
    --model_cond_config_path configs/synth_u/cond/text_msmdiffmv.yaml \
    --train_config_path configs/synth_u/train.yaml \
    --evaluate_config_path configs/synth_u/evaluate.yaml \
    --data_folder /playpen/haochenz/LitsDatasets/128_len_ts/synthetic_u \
    --clip_folder "" \
    --multipatch_num 3 \
    --L_patch_len 2 \
    --base_patch 4 \
    --epochs 2500 \
    --batch_size 512 \
    --clip_cache_path "" \
    --only_evaluate True \
    --samples_name "verbalts_caps_samples.pt"