model:
  target: Models.interpretable_diffusion.gaussian_diffusion.Diffusion_TS
  params:
    seq_length: 128
    feature_size: 1
    n_layer_enc: 3
    n_layer_dec: 2
    d_model: 64  # 4 X 16
    timesteps: 500
    sampling_timesteps: 500
    loss_type: 'l1'
    beta_schedule: 'cosine'
    n_heads: 4
    mlp_hidden_times: 4
    attn_pd: 0.0
    resid_pd: 0.0
    kernel_size: 1
    padding_size: 0


solver:
  base_lr: 1.0e-5
  max_epochs: 18000
  results_folder: ./results/synth_u
  

dataloader:
  train_dataset:
    target: Utils.Data_utils.npy_datasets.PreSplitNPYDataset
    params:
      name: synth_u
      data_root: ../data/synthetic_u
      split: train  # seq_length

  valid_dataset:
    target: Utils.Data_utils.npy_datasets.PreSplitNPYDataset
    params:
      name: synth_u
      data_root: ../data/synthetic_u
      split: valid  # seq_length


  test_dataset:
    target: Utils.Data_utils.npy_datasets.PreSplitNPYDataset
    params:
      name: synth
      data_root: ../data/synthetic_u
      split: test  # seq_length
    coefficient: 1.0e-2
    step_size: 5.0e-2
    sampling_steps: 200

  batch_size: 512
  sample_size: 256